# Generated by Django 3.2.3 on 2021-06-18 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_setup_data'),
    ]

    operations = [
        # アプリからデータアクセスを許可する（tenant_usersは必須）
        migrations.RunSQL("""
            GRANT select, insert ON tenant_users TO tenantuser;
            GRANT select, insert ON tenants TO tenantuser;
            GRANT select, insert ON customers TO tenantuser;
            GRANT select, insert ON tenant_users_groups TO tenantuser;
            GRANT select, insert ON tenant_users_user_permissions TO tenantuser;
        """,
        reverse_sql="""
            REVOKE select, insert ON tenant_users FROM tenantuser;
            REVOKE select, insert ON tenants FROM tenantuser;
            REVOKE select, insert ON customers FROM tenantuser;
            REVOKE select, insert ON tenant_users_groups FROM tenantuser;
            REVOKE select, insert ON tenant_users_user_permissions FROM tenantuser;
        """),
        # 所属テナントのデータのみを見せたい場合、各テーブルにRLSを設定
        migrations.RunSQL("""
            ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
            CREATE POLICY tenantuser_customers ON customers USING(tenant_id::text = current_user);
            ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
            CREATE POLICY tenantuser_tenants ON tenants USING(id::text = current_user);
            ALTER TABLE tenant_users ENABLE ROW LEVEL SECURITY;
            CREATE POLICY tenantuser_tenantusers ON tenant_users USING(tenant_id::text = current_user);
        """,
        reverse_sql='''
            ALTER TABLE customers DISABLE ROW LEVEL SECURITY;
            DROP POLICY tenantuser_customers ON customers;
            ALTER TABLE tenants DISABLE ROW LEVEL SECURITY;
            DROP POLICY tenantuser_tenants ON tenants;
            ALTER TABLE tenant_users DISABLE ROW LEVEL SECURITY;
            DROP POLICY tenantuser_tenantusers ON tenant_users;
        ''')
    ]
